version: '3.8'

services:
  varzealeague.application:
    image: ${DOCKER_REGISTRY-}varzealeagueapplication
    build:
      context: .
      dockerfile: VarzeaTeam.Application\Dockerfile
    container_name: varzeaLeague_api_container
    networks: 
      - elastic
    depends_on: 
      - mongodb
    ports:
      - "8080:80"

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge