name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Run Unit Tests
        run: |
          echo "Running unit tests..."
          docker build --target test -t varzeateam/test:latest -f VarzeaTeam.Application/Dockerfile .
          docker run --rm -v ${{ github.workspace }}/coverage:/app/TestResults varzeateam/test:latest

      - name: Debug - List all files in the workspace
        run: find ${{ github.workspace }} -type f

      - name: Debug - List coverage directory
        run: ls -R ./coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: coverage

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: /tmp/.docker-cache

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: docker build --tag varzeateam/application:latest -f VarzeaTeam.Application/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Clean Up Docker Images
        run: docker rmi varzeateam/application:latest

  Validator:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore VarzeaTeam.Application/VarzeaLeague.Application.csproj

      - name: Run Code Analysis
        run: dotnet build VarzeaTeam.Application/VarzeaLeague.Application.csproj /p:EnableCodeAnalysis=true /p:RunAnalyzersDuringBuild=true

      - name: Upload Validator Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: validator-results
          path: bin/Debug/validator-results
