name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image for Tests
        run: |
          echo "Building Docker image for tests..."
          docker build --target test -t varzeateam/test:latest -f VarzeaTeam.Application/Dockerfile .

      - name: Run Tests in Docker Container
        run: |
          echo "Running tests in Docker container..."
          docker run --name varzeateam_test_container varzeateam/test:latest

      - name: List Files in Coverage Directory
        run: |
          echo "Listing files in coverage directory..."
          docker exec varzeateam_test_container ls -la /app/TestResults/

      - name: Copy Coverage Report
        run: |
          echo "Copying coverage report..."
          mkdir -p coverage
          docker cp varzeateam_test_container:/app/TestResults/coverage.cobertura.xml ./coverage/Cobertura.xml

      - name: Remove Docker Container
        run: |
          echo "Removing Docker container..."
          docker rm varzeateam_test_container

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src/VarzeaTeam.Test/TestResults

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: /tmp/.docker-cache

      - name: Upload Coverage Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: coverage/Cobertura.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/Cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '85 100'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: docker build --tag varzeateam/application:latest -f VarzeaTeam.Application/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Clean Up Docker Images
        run: docker rmi varzeateam/application:latest

  Validator:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore Dependencies
        run: dotnet restore VarzeaTeam.Application/VarzeaLeague.Application.csproj

      - name: Run Code Analysis
        run: dotnet build VarzeaTeam.Application/VarzeaLeague.Application.csproj /p:EnableCodeAnalysis=true /p:RunAnalyzersDuringBuild=true

      - name: Upload Validator Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: validator-results
          path: bin/Debug/validator-results
