name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.build-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build --tag varzeateam_application:latest -f VarzeaTeam.Application/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          docker run --rm varzeateam_application:latest sh -c "dotnet test /src/VarzeaTeam.Test/VarzeaLeague.Test.csproj --logger:trx"
      
      - name: Print Docker logs
        if: failure()
        run: |
          echo "Printing Docker logs for debugging..."
          docker logs varzeateam_application:latest

      - name: Clean up
        run: docker rmi varzeateam_application:latest
