name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Test Image
        run: |
          echo "Building test image..."
          docker build --target test -t VarzeaTeam/test:latest -f VarzeaTeam.Application/Dockerfile .

      - name: Verify Directory Structure
        run: |
          echo "Verifying directory structure..."
          CONTAINER_ID=$(docker ps -qf "name=varzeaLeague_api_container")
          docker exec -i $CONTAINER_ID /bin/bash -c "ls /src/VarzeaTeam.Test"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./TestResults

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: docker build --tag varzeateam/application:latest -f VarzeaTeam.Application/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Clean Up Docker Images
        run: docker rmi varzeateam/application:latest

  Validator:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore Dependencies
        run: dotnet restore VarzeaTeam.Application/VarzeaLeague.Application.csproj

      - name: Run Code Analysis
        run: dotnet build VarzeaTeam.Application/VarzeaLeague.Application.csproj /p:EnableCodeAnalysis=true /p:RunAnalyzersDuringBuild=true

      - name: Upload Validator Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: validator-results
          path: bin/Debug/validator-results
