name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Run Unit Tests and Collect Coverage
        run: |
          echo "Running unit tests and collecting code coverage..."
          docker build --target test -t varzeateam/test:latest -f VarzeaTeam.Application/Dockerfile .
          docker run --rm -v ${{ github.workspace }}:/workspace varzeateam/test:latest

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src/VarzeaTeam.Test/TestResults

      - name: Check Code Coverage
        run: |
          echo "Checking code coverage..."
          coverage_file=$(find src/VarzeaTeam.Test/TestResults -name 'coverage.cobertura.xml' | head -n 1)
          if [ -z "$coverage_file" ]; then
            echo "Coverage report not found!"
            exit 1
          fi
          coverage_percentage=$(grep -o 'line-rate="[0-9.]*"' "$coverage_file" | head -1 | cut -d'"' -f2)
          coverage_percentage=$(echo "$coverage_percentage * 100" | bc)
          if (( $(echo "$coverage_percentage < 85" | bc -l) )); then
            echo "Code coverage is below 85%: ${coverage_percentage}%"
            exit 1
          else
            echo "Code coverage is sufficient: ${coverage_percentage}%"
          fi

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: /tmp/.docker-cache

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: docker build --tag varzeateam/application:latest -f VarzeaTeam.Application/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Clean Up Docker Images
        run: docker rmi varzeateam/application:latest

  Validator:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore Dependencies
        run: dotnet restore VarzeaTeam.Application/VarzeaLeague.Application.csproj

      - name: Run Code Analysis
        run: dotnet build VarzeaTeam.Application/VarzeaLeague.Application.csproj /p:EnableCodeAnalysis=true /p:RunAnalyzersDuringBuild=true

      - name: Upload Validator Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: validator-results
          path: bin/Debug/validator-results
