name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.build-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build --tag varzeateam_application:latest -f VarzeaTeam.Application/Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Clean up
        run: docker rmi varzeateam_application:latest varzeateam_test:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run unit tests
        continue-on-error: false
        run: |
          echo "Running unit tests..."
          docker build --target test -t varzeateam_test:latest -f VarzeaTeam.Application/Dockerfile .
          docker run --rm varzeateam_test:latest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src/VarzeaTeam.Test/TestResults
