name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.build-cache
      #     key: ${{ runner.os }}-docker-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build --tag varzeaLeague_api_container:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Run unit tests
        run: docker run --rm varzeaLeague_api_container:latest sh -c "run-your-unit-tests-command"
